spring:
  application:
    name: bankcards
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:bank_db}
    username: ${POSTGRES_USER:bank_user}
    password: ${POSTGRES_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

server:
  port: 8080

jwt:
  secret: VerySecretKeyThatShouldBeAtLeast32BytesLongForHS256Algorithm
  expiration: 3600000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html